"""update card table

Revision ID: 74674a1ad22f
Revises: 0d7de7a64237
Create Date: 2025-09-14 16:38:51.440644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74674a1ad22f'
down_revision: Union[str, Sequence[str], None] = '0d7de7a64237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('ease_factor', sa.Float(), nullable=False))
    op.add_column('cards', sa.Column('interval', sa.Integer(), nullable=False))
    op.add_column('cards', sa.Column('repetitions', sa.Integer(), nullable=False))
    op.add_column('cards', sa.Column('lapses', sa.Integer(), nullable=False))
    op.add_column('cards', sa.Column('due_at', sa.DateTime(), nullable=False))
    op.add_column('cards', sa.Column('suspended', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'suspended')
    op.drop_column('cards', 'due_at')
    op.drop_column('cards', 'lapses')
    op.drop_column('cards', 'repetitions')
    op.drop_column('cards', 'interval')
    op.drop_column('cards', 'ease_factor')
    # ### end Alembic commands ###
